- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: apache2 installation
    apt:
      name: apache2
      state: present
  - name: start the apache2 service
    service:
      name: apache2
      state: started
  - name: deploy the code
    copy:
      src: /home/ubuntu/index.html
      dest: /var/www/html/index.html
